<SimplePopup>:
    id:pop
    password: pass_box
    TextInput: 
        id: pass_box
        font_size: 20
        size_hint: 1, 0.55
        pos_hint: {"x":0, "top":1}
        multiline: False
        password: True
        on_text_validate:app.get(root.password.text)
    Button:
        id:exit
        text: "OK"
        # set size of the button
        size_hint: 1, 0.25
        # set position of the button   
        pos_hint: {"x":0.0, "y":0.2}
        on_press:app.get(root.password.text)

FloatLayout: 
    Image: 
        source: 'image/lbTitle.jpg' 
        pos_hint: {"x":-0.0, "top":1.3}
        width:200
        height:100

    Image: 
        source: 'image/btTime.jpg' 
        pos_hint: {"x":-0.5, "top":0.62}
        width:1000
        height:250
        size_hint: None, None 

    Label:
        id: stopwatch 
        text: '00:00:00'
        pos_hint: {"x":0, "top":0.95}
        font_size: 100
        font_name: 'Roboto'
        markup: True  
        
    Button: 
        text:"Restart"
        background_color: (100/255.0,100/255.0,51/255.0,0.2) if self.state == 'normal' else (1,0,0,1)
        background_normal: ""
        pos_hint: {"x":0.6, "top":0.2}
        border: 15, 15, 30, 30
        font_name: 'Roboto'
        bold: True
        border_radius:[30]
        font_size: 20
        size: 150, 100
        size_hint: None, None
        on_press: app.restart()
  
    Button: 
        text:"Shutdown"
        background_color: (100/255.0,100/255.0,51/255.0,0.2) if self.state == 'normal' else (1,0,0,1)
        background_normal: ""
        pos_hint: {"x":0.1, "top":0.2}
        font_name: 'Roboto'
        bold: True
        font_size: 20
        size: 150, 100
        size_hint: None, None
        on_press: app.shut_down()